### ISSUE TITLE
add VB.net to the index in readme

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/tcso#23]
Add VB.net (https://github.com/gautamkrishnar/tcso/tree/master/VB.NET) to the list of available languages in https://github.com/gautamkrishnar/tcso/blob/master/README.md

**Comment by asantospt** [comment]
Can I take this? @gautamkrishnar

**Comment by p-murli** [comment]
Hey. I've added the link for VB.NET to the list of available languages. Could you review it and check if its alright?

**Comment by gautamkrishnar** [comment]
@a-santos thanks for your intrest. @p-murli already opened a PR. Please feel free to work on any other issues/new programming langs.
