### ISSUE TITLE
Add angular to readme.md

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/tcso#26]
Add angular tcso link (https://github.com/gautamkrishnar/tcso/tree/master/Angular) to the main readme.md

**Comment by ahmedasmar** [comment]
@gautamkrishnar Done ;)

**Comment by gautamkrishnar** [comment]
@Hax7  So fast! 😄  Thanks!

**Comment by ahmedasmar** [comment]
happy to help :)
