### ISSUE TITLE
Haskell

### ISSUE THREAD

**Issue by nischkar** [gautamkrishnar/tcso#6]
Please create a tcso for haskell

**Comment by doriancodes** [comment]
Done :) https://github.com/gautamkrishnar/tcso/pull/35

**Comment by gautamkrishnar** [comment]
@alodavi Awesome! thanks for implementing this 👍  This was open for a long time...

**Comment by gautamkrishnar** [comment]
Closing this #35

**Comment by doriancodes** [comment]
thanks! It was fun :)
