### ISSUE TITLE
Create a script that automaticially updates the readme.md

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/tcso#73]
Create a script that automaticially updates the [README.md](./https://github.com/gautamkrishnar/tcso/blob/master/README.md) index it is run, with the list of languages available in each folder.  Use node.js to do the same.

**Comment by Progressandro** [comment]
I'd like to contribute with this, but I don't quite understand what you need. Could you please ellaborate? I think this was already added over here:

https://github.com/gautamkrishnar/tcso/blob/2db9cae45ad3c97245a7c1b78bc6f27379d234d1/update-readme#L32

**Comment by gautamkrishnar** [comment]
Oops sorry i totally forgot about this one. Thanks a lot for pointing it out @Progressandro

**Comment by gautamkrishnar** [comment]
Duplicate of #59 which was fixed in #64
